### PR TITLE
feat(schematics): add template support

### PR DESCRIPTION
**Pull request by sumitparakh**
* **Please check if the PR fulfills these requirements**
- [x] The commit message is clear and concise
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs/Readme have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updated schematics definition for template

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
User will be opted to select a list of python framework, for which he wants to create application. Default is **none**

* **Other information**:

This is how user will be asked to select a framework:-
image

### CODE REVIEW

**Comment by sumitparakh** [comment]
Hi @alphacentauri82, I've started working on adding template support. But I was thinking if we should allow users to choose django versions or not.   What do you think? 

Or, should we add version selection in the next phase?

Check this screenshot for more reference:-
image

https://docs.djangoproject.com/en/3.1/faq/install/#what-are-django-s-prerequisites

**Comment by alphacentauri82** [comment]
I think for now go with the latest two versions and then I can pitch in for selecting versions. this is an amazing job. Thank you so much @sumitparakh

**Comment by sumitparakh** [comment]
This PR depends on #16

**Comment by alphacentauri82** [comment]
@sumitparakh merged! - ready to undraft?

**Pull request merged**
